"""Promotion-specific resource spends and class-track actions."""

from __future__ import annotations

import math
from typing import Any

from src.core.randomness import gameplay_random as random

from .meters import (
    _maybe_preserve,
    _preserve_spent_meter,
    _set_target_stacks,
    _spend_mp,
    _target_key,
    _target_stacks,
    cap_for,
    gain_meter,
    spend_meter,
)
from .state import (
    CASE_MILESTONES,
    _claim_action,
    _cleanse_one_hostile_status,
    _has_skill,
    _ring_awakened_equipped,
    class_name,
    combat_state,
    ensure_state,
)

MARTIAL_KI_ACTIONS = frozenset(
    {
        "Double Strike",
        "Leg Sweep",
        "True Strike",
        "Uppercut",
        "Headbutt",
        "Hyakuretsukyaku",
        "Triple Strike",
        "Spinning Back Elbow",
        "Suplex",
        "Hadouken",
    }
)

RISKY_LUCK_ACTIONS = frozenset(
    {
        "Steal",
        "Mug",
        "Gold Toss",
        "Slot Machine",
        "Sneak Attack",
        "Pocket Sand",
        "Kidney Punch",
        "Sleeping Powder",
        "Pilfering Strike",
        "Dirty Trick",
    }
)
STATUS_LUCK_ACTIONS = frozenset(
    {
        "Pocket Sand",
        "Kidney Punch",
        "Sleeping Powder",
    }
)
KI_SPEND_ABILITIES = frozenset(
    {
        "Chi Heal",
        "Leg Sweep",
        "Hyakuretsukyaku",
        "Suplex",
        "Hadouken",
    }
)


def _power_up_active(character: Any, name: str) -> bool:
    effect = getattr(character, "class_effects", {}).get("Power Up")
    return bool(
        getattr(character, "power_up", False)
        and _has_skill(character, name)
        and effect is not None
        and getattr(effect, "active", False)
    )


def _apply_ordered_blessing(character: Any, spent: int) -> str:
    if not _ring_awakened_equipped(character, "Templar"):
        return ""
    from .. import class_rings

    blessing = class_rings.next_ordered_blessing(character)
    if not blessing:
        return ""
    empowered = _power_up_active(character, "Holy Retribution")
    scale = 1.25 if empowered else 1.0
    duration = 3 if empowered else 2
    from ..cleric import has_cleric_talent

    if has_cleric_talent(character, "templar.ordered-purpose"):
        scale *= 1.25
        duration += 1
    if blessing == "Regen":
        effect = character.magic_effects["Regen"]
        effect.active = True
        effect.duration = max(effect.duration, duration)
        effect.extra = max(int(effect.extra or 0), int(4 * spent * scale))
    elif blessing == "Defense":
        effect = character.stat_effects["Defense"]
        effect.active = True
        effect.duration = max(effect.duration, duration)
        effect.extra = max(int(effect.extra or 0), int(3 * spent * scale))
    else:
        combat_state(character)["ordered_blessing_counter"] = {
            "damage": max(1, int(6 * spent * scale)),
            "turns": duration,
        }
    message = f"Ordered Blessings advances through {blessing}.\n"
    if has_cleric_talent(character, "templar.perfect-order"):
        effect = character.stat_effects["Magic Defense"]
        effect.active = True
        effect.duration = max(int(effect.duration or 0), duration)
        effect.extra = max(int(effect.extra or 0), max(2, spent * 2))
        effect.source = "Perfect Order"
        message += "Perfect Order raises Magic Defense.\n"
    if has_cleric_talent(character, "templar.liturgical-renewal"):
        mana = character.mana
        restored = min(
            max(0, int(mana.max) - int(mana.current)),
            max(1, spent),
        )
        mana.current += restored
        if restored:
            message += f"Liturgical Renewal restores {restored} MP.\n"
    return message


def conviction_action(character: Any, action_name: str, *, clean: bool = False) -> str:
    """Record Conviction generated by a valid signature-vow action."""
    if class_name(character) not in {"Paladin", "Crusader"}:
        return ""
    if clean:
        return gain_meter(
            character,
            "oath_conviction",
            1,
            f"clean {action_name} outcome",
        )
    return gain_meter(character, "oath_conviction", 1, action_name)


def add_fortune(character: Any, success: bool, reason: str) -> str:
    if class_name(character) not in {"Thief", "Rogue"}:
        return ""
    return gain_meter(character, "fortune" if success else "misfortune", 1, reason)


def record_luck_roll(
    character: Any,
    success: bool,
    reason: str,
    *,
    incoming: bool = False,
) -> str:
    """Record one meaningful luck outcome per player or hostile action."""
    if class_name(character) not in {"Thief", "Rogue"}:
        return ""
    if not _claim_action(character, "luck_outcome", incoming=incoming):
        return ""
    outcome = "clean success" if success else "setback"
    message = add_fortune(character, success, f"{reason} {outcome}")
    if success:
        from ..thief import has_thief_talent

        if has_thief_talent(character, "thief.read-the-room"):
            import random

            if random.random() < 0.25:
                message += gain_meter(character, "fortune", 1, "Read the Room")
    return message


def consume_fortune_for_risky_action(character: Any, reason: str) -> tuple[float, str]:
    """Spend Fortune before an eligible action and return its reliability bonus."""
    if class_name(character) not in {"Thief", "Rogue"}:
        return 0.0, ""
    if reason not in RISKY_LUCK_ACTIONS:
        return 0.0, ""
    state = combat_state(character)
    spent = int(state.get("fortune", 0) or 0)
    if spent <= 0:
        return 0.0, ""
    state["fortune"] = 0
    state["pending_fortune_payoff"] = {
        "spent": spent,
        "reason": reason,
    }
    from ..thief import has_thief_talent

    per_stack = 0.05
    if has_thief_talent(character, "thief.gilt-edge"):
        per_stack += 0.025
    if has_thief_talent(character, "rogue.stacked-odds"):
        per_stack += 0.025
    reliability = min(0.30, per_stack * spent)
    msg = f"{character.name} spends {spent} Fortune smoothing {reason}."
    msg += " The odds turn in their favor.\n"
    return reliability, msg


def finish_fortune_payoff(character: Any, success: bool) -> str:
    """Resolve ring preservation only after the prepared risky action succeeds."""
    state = combat_state(character)
    pending = state.get("pending_fortune_payoff")
    state["pending_fortune_payoff"] = None
    if not success or not isinstance(pending, dict):
        return ""
    message = _preserve_spent_meter(
        character,
        "fortune",
        "Rogue",
        "Loaded Dice",
        "",
    )
    from ..thief import has_thief_talent

    if (
        has_thief_talent(character, "thief.fortune-favors-bold")
        and int(combat_state(character).get("fortune", 0) or 0) == 0
    ):
        combat_state(character)["fortune"] = 1
        message += "Fortune Favors the Bold preserves 1 spent Fortune.\n"
    return message


def resolve_misfortune_payoff(
    character: Any,
    target: Any | None,
    base_damage: int,
    reason: str,
    *,
    result: Any | None = None,
) -> str:
    if class_name(character) not in {"Thief", "Rogue"}:
        return ""
    state = combat_state(character)
    spent = int(state.get("misfortune", 0) or 0)
    if spent <= 0:
        return ""
    state["misfortune"] = 0
    from ..thief import has_thief_talent

    per_stack = 0.08
    if has_thief_talent(character, "thief.hard-lessons"):
        per_stack += 0.02
    if has_thief_talent(character, "rogue.cruel-reversal"):
        per_stack += 0.02
    bonus = max(1, int(max(1, base_damage) * (per_stack * spent)))
    if target is not None and base_damage > 0:
        hit, defense_message, defended = target.handle_defenses(
            character,
            bonus,
            typ="Physical",
        )
        applied = 0
        reduction_message = ""
        if hit and defended > 0:
            hit, reduction_message, reduced = target.damage_reduction(
                defended,
                character,
                typ="Physical",
            )
            if hit and reduced > 0:
                applied = min(int(target.health.current), max(0, int(reduced)))
                target.health.current = max(0, int(target.health.current) - applied)
                if applied:
                    character._emit_damage_event(
                        target,
                        applied,
                        "Physical",
                        source="promotion_kit_payoff",
                        attack_source="skill",
                        ability_name=reason,
                    )
        msg = defense_message + reduction_message
        msg += (
            f"{character.name} cashes in {spent} Misfortune through {reason} "
            f"for {applied} extra pressure.\n"
        )
    else:
        scaled_detail = ""
        extra = getattr(result, "extra", {}) if result is not None else {}
        stolen_gold = (
            max(0, int(extra.get("stolen_gold", 0) or 0)) if isinstance(extra, dict) else 0
        )
        if target is not None and stolen_gold:
            gold_bonus = min(
                max(0, int(getattr(target, "gold", 0) or 0)),
                max(1, int(stolen_gold * 0.10 * spent)),
            )
            if gold_bonus:
                target.gold -= gold_bonus
                character.gold += gold_bonus
                scaled_detail = f", including {gold_bonus} extra gold"
        if target is not None and result is not None:
            effects = getattr(result, "effects_applied", {}) or {}
            for names in effects.values() if isinstance(effects, dict) else ():
                for name in names if isinstance(names, list) else ():
                    effect = target.effect_handler(name).get(name)
                    if effect is not None and int(getattr(effect, "duration", 0) or 0) > 0:
                        effect.duration += spent
                        if has_thief_talent(character, "thief.spiteful-streak"):
                            effect.duration += 1
                        scaled_detail = f", extending {name}"
        msg = (
            f"{character.name} cashes in {spent} Misfortune through {reason} "
            f"for a stronger payoff{scaled_detail}.\n"
        )
    return _preserve_spent_meter(character, "misfortune", "Rogue", "Loaded Dice", msg)


def misfortune_severity_multiplier(character: Any) -> float:
    """Preview stored Misfortune for effects that scale inside their resolver."""
    if class_name(character) not in {"Thief", "Rogue"}:
        return 1.0
    stored = int(combat_state(character).get("misfortune", 0) or 0)
    from ..thief import has_thief_talent

    per_stack = 0.08
    if has_thief_talent(character, "thief.hard-lessons"):
        per_stack += 0.02
    if has_thief_talent(character, "rogue.cruel-reversal"):
        per_stack += 0.02
    if has_thief_talent(character, "rogue.rigged-reels"):
        per_stack *= 1.25
    return 1.0 + (per_stack * stored)


def cheat_death(character: Any) -> str:
    if class_name(character) != "Rogue" or not _has_skill(character, "Cheat Death"):
        return ""
    state = combat_state(character)
    if state.get("cheat_death_used"):
        return ""
    state["cheat_death_used"] = True
    misfortune = int(state.get("misfortune", 0) or 0)
    from ..thief import has_thief_talent

    chance = 0.25 + (0.10 * misfortune)
    if has_thief_talent(character, "rogue.cheat-fate"):
        chance += 0.10
    chance = min(0.75, chance)
    try:
        import random

        success = random.random() < chance
    except Exception:
        success = False
    loaded_dice = False
    if not success:
        try:
            from .. import class_rings

            loaded_dice = class_rings.loaded_dice_succeeds(character)
        except Exception:
            loaded_dice = False
        success = loaded_dice
    if not success:
        return "Cheat Death fails to find a way out.\n"
    state["misfortune"] = 0
    state["jinx_turns"] = 1 if has_thief_talent(character, "rogue.break-the-jinx") else 2
    character.health.current = 1
    msg = "Loaded Dice turns the failed save.\n" if loaded_dice else ""
    if misfortune > 0:
        msg += f"Cheat Death spends {misfortune} Misfortune and "
    else:
        msg += "Cheat Death "
    msg += f"leaves {character.name} standing at 1 HP under Jinx.\n"
    if misfortune <= 0:
        return msg
    return _preserve_spent_meter(character, "misfortune", "Rogue", "Loaded Dice", msg)


def jinx_accuracy_modifier(character: Any) -> float:
    """Return the risky accuracy penalty while Cheat Death's Jinx lingers."""
    return -0.10 if int(combat_state(character).get("jinx_turns", 0) or 0) > 0 else 0.0


def jinx_luck_multiplier(character: Any) -> float:
    """Return the luck-check multiplier while Cheat Death's Jinx lingers."""
    return 0.75 if int(combat_state(character).get("jinx_turns", 0) or 0) > 0 else 1.0


def apply_death_mark(character: Any, target: Any, reason: str = "setup") -> str:
    cap = cap_for(character, "death_marks")
    if cap <= 0 or target is None:
        return ""
    state = combat_state(character)
    marks = state.setdefault("death_marks", {})
    before = _target_stacks(marks, target)
    after = min(cap, before + 1)
    _set_target_stacks(marks, target, after)
    if after == before:
        return f"Death Mark is capped at {cap}.\n"
    return f"{target.name} gains a Death Mark from {reason} ({after}/{cap}).\n"


DEATH_MARK_SETUP_ABILITIES = frozenset(
    {
        "Backstab",
        "Sneak Attack",
        "Momentum",
        "Kidney Punch",
        "Disembowel",
        "Marked Shuriken",
    }
)
DEATH_MARK_FINISHERS = frozenset({"Deathblow", "Thousand Cuts", "Death Sentence"})
DEATH_MARK_ACTION_REGISTRY = {
    **{name: "setup" for name in DEATH_MARK_SETUP_ABILITIES},
    **{name: "finisher" for name in DEATH_MARK_FINISHERS},
}


def _claim_death_mark_action(character: Any, ability_name: str, role: str) -> bool:
    """Claim one authored Death Mark resolution for the current action token."""
    if DEATH_MARK_ACTION_REGISTRY.get(ability_name) != role:
        return False
    state = combat_state(character)
    token = int(state.get("action_token", 0) or 0)
    if token <= 0:
        return True
    key = (token, role, ability_name)
    claimed = state.setdefault("death_mark_action_tokens", set())
    if key in claimed:
        return False
    claimed.add(key)
    return True


def death_mark_stacks(character: Any, target: Any) -> int:
    """Return Death Marks currently attached to one combat target."""
    if target is None:
        return 0
    return _target_stacks(combat_state(character).get("death_marks"), target)


def clear_death_marks(character: Any, target: Any) -> None:
    """Remove Death Marks from one target without disturbing other enemies."""
    if target is not None:
        _set_target_stacks(combat_state(character).setdefault("death_marks", {}), target, 0)


def resolve_death_mark_setup(
    character: Any,
    target: Any,
    ability_name: str,
    *,
    hit: bool,
    status_applied: bool = False,
) -> str:
    """Award at most two marks after a declared setup action completes."""
    if (
        ability_name not in DEATH_MARK_SETUP_ABILITIES
        or not hit
        or target is None
        or not target.is_alive()
        or class_name(character) not in {"Assassin", "Ninja"}
        or not _claim_death_mark_action(character, ability_name, "setup")
    ):
        return ""
    msg = apply_death_mark(character, target, ability_name)
    if status_applied:
        msg += apply_death_mark(character, target, f"{ability_name} status")
    return msg


def begin_death_mark_finisher(character: Any, target: Any, ability_name: str) -> tuple[int, str]:
    """Spend every mark when a validated dedicated finisher is attempted."""
    if ability_name not in DEATH_MARK_FINISHERS or target is None:
        return 0, ""
    if not _claim_death_mark_action(character, ability_name, "finisher"):
        return 0, "Death Mark finisher already resolved for this action.\n"
    stacks = death_mark_stacks(character, target)
    if stacks <= 0:
        return 0, "Death Mark setup is required before using this finisher.\n"
    clear_death_marks(character, target)
    return stacks, f"{character.name} spends {stacks} Death Mark(s) on {ability_name}.\n"


def resolve_weapon_finisher(
    character: Any,
    target: Any,
    ability_name: str,
    marks: int,
    base_damage: int,
    *,
    mana_cost: int,
    hit: bool,
) -> str:
    """Apply the shared marked damage and Execution Rhythm refund."""
    if not hit or marks <= 0 or target is None or base_damage <= 0:
        return ""
    bonus = max(1, int(base_damage * 0.12 * marks))
    target.health.current = max(0, target.health.current - bonus)
    msg = f"{ability_name} releases {marks} Death Mark(s) for {bonus} execution damage.\n"
    if _has_skill(character, "Execution Rhythm") and mana_cost > 0:
        refund = max(1, int(mana_cost * 0.10 * marks))
        before = int(character.mana.current)
        character.mana.current = min(int(character.mana.max), before + refund)
        restored = int(character.mana.current) - before
        if restored:
            msg += f"Execution Rhythm restores {restored} MP.\n"
    return msg


def resolve_death_contest(
    actor: Any,
    target: Any,
    *,
    marks: int = 0,
    actor_divisor: int = 4,
    actor_roll_multiplier: float = 1.0,
    rng: Any = random,
) -> tuple[bool, bool]:
    """Resolve the shared Charisma-versus-Constitution Death contest.

    Returns a pair of ``(killed, immune)``. Bosses and targets at full Death
    resistance are always immune; negative resistance strengthens the caster.
    """
    try:
        from ...enemies import is_boss_enemy

        boss = is_boss_enemy(target)
    except Exception:
        boss = bool(getattr(target, "boss", False) or getattr(target, "is_boss", False))
    resistance = float(target.check_mod("resist", enemy=actor, typ="Death"))
    if boss or resistance >= 1.0 or "Death" in getattr(target, "status_immunity", ()):
        return False, True
    actor_max = max(1, int(actor.stats.charisma) // max(1, int(actor_divisor)))
    actor_roll = rng.randint(0, actor_max)
    actor_roll = int(
        actor_roll
        * max(0.0, float(actor_roll_multiplier))
        * (1.0 - resistance)
        * (1.20 ** max(0, int(marks)))
    )
    target_roll = rng.randint(max(0, target.stats.con // 2), max(1, target.stats.con))
    target_roll += target.check_mod("luck", enemy=actor, luck_factor=10)
    from .. import mage_mechanics

    target_roll = int(target_roll * mage_mechanics.save_roll_multiplier(target))
    if actor_roll <= target_roll:
        return False, False
    target.health.current = 0
    return True, False


def begin_no_trace_opener(character: Any, target: Any) -> tuple[int, float, str]:
    """Prepare the awakened Ninja ring's first standard Ninja Blade attack."""
    weapon = getattr(character, "equipment", {}).get("Weapon")
    state = combat_state(character)
    if (
        class_name(character) != "Ninja"
        or getattr(weapon, "subtyp", None) != "Ninja Blade"
        or not state.get("has_initiative", False)
    ):
        return 0, 1.0, ""
    from .. import class_rings

    multiplier = class_rings.first_strike_multiplier(character, has_initiative=True)
    if multiplier <= 1.0:
        return 0, 1.0, ""
    msg = apply_death_mark(character, target, "No-Trace Opener")
    marks = death_mark_stacks(character, target)
    clear_death_marks(character, target)
    msg += f"{character.name} spends {marks} Death Mark(s) on No-Trace Opener.\n"
    return marks, multiplier, msg


def finish_no_trace_opener(character: Any, target: Any, *, marks: int, hit: bool) -> str:
    """Preserve one opener mark after a successful nonlethal payoff."""
    if not hit or marks <= 0 or target is None or not target.is_alive():
        return ""
    lines: list[str] = []
    _maybe_preserve(
        character,
        "death_marks",
        "Ninja",
        "No-Trace Opener",
        lines,
        target=target,
    )
    return "".join(lines)


def add_revelation(character: Any, target: Any, amount: int = 1, reason: str = "insight") -> str:
    cap = cap_for(character, "revelation")
    if cap <= 0 or target is None:
        return ""
    state = combat_state(character)
    mapping = state.setdefault("revelation", {})
    before = _target_stacks(mapping, target)
    after = min(cap, before + amount)
    _set_target_stacks(mapping, target, after)
    if after == before:
        return f"Revelation is capped at {cap}.\n"
    return f"{character.name} gains Revelation on {target.name} from {reason} ({after}/{cap}).\n"


REVELATION_PRECISION_ACTIONS = frozenset(
    {
        "Piercing Strike",
        "True Strike",
        "True Piercing Strike",
    }
)
INVESTIGATION_SETUP_ACTIONS = frozenset(
    {
        "Silence",
        "Dispel",
        "Enfeeble",
        "Weaken Mind",
    }
)


def _has_track_talent(character: Any, key: str) -> bool:
    try:
        from ...progression import has_talent

        return has_talent(character, key)
    except (AttributeError, KeyError, TypeError, ValueError):
        return False


def revelation_stacks(character: Any, target: Any) -> int:
    """Return combat-only Revelation stored against one target."""
    mapping = combat_state(character).get("revelation", {})
    return _target_stacks(mapping, target) if isinstance(mapping, dict) else 0


def clear_revelation(character: Any, target: Any | None = None) -> None:
    """Clear one target's Revelation, or all Revelation when target is omitted."""
    state = combat_state(character)
    mapping = state.setdefault("revelation", {})
    if target is None:
        mapping.clear()
        state["active_revelation_payoff"] = None
        return
    mapping.pop(_target_key(target), None)
    pending = state.get("active_revelation_payoff")
    if isinstance(pending, dict) and pending.get("target_key") == _target_key(target):
        state["active_revelation_payoff"] = None


def prepare_revelation_payoff(
    character: Any,
    target: Any,
    *,
    basic_attack: bool = False,
) -> tuple[float, float, str]:
    """Consume Revelation before an eligible weapon payoff resolves."""
    if target is None or class_name(character) not in {"Inquisitor", "Seeker"}:
        return 0.0, 1.0, ""
    state = combat_state(character)
    action = str(state.get("action_choice") or state.get("action_name") or "")
    if not (basic_attack or action == "Exploit Weakness" or action in REVELATION_PRECISION_ACTIONS):
        return 0.0, 1.0, ""
    target_key = _target_key(target)
    active = state.get("active_revelation_payoff")
    if isinstance(active, dict) and active.get("target_key") == target_key:
        stacks = int(active.get("stacks", 0) or 0)
        return float(active.get("accuracy", 0.0)), 1.0 + (0.05 * stacks), ""
    if not _claim_action(character, "revelation_payoff"):
        return 0.0, 1.0, ""
    stacks = revelation_stacks(character, target)
    studied_accuracy = (
        0.10 if action == "Exploit Weakness" and case_progress(character, target) >= 50 else 0.0
    )
    if stacks <= 0:
        return (
            studied_accuracy,
            1.0,
            (
                f"{character.name}'s Weakness Brief steadies the exploit.\n"
                if studied_accuracy
                else ""
            ),
        )
    mapping = state.setdefault("revelation", {})
    mapping.pop(target_key, None)
    accuracy_per_stack = 0.05 if _has_track_talent(character, "seeker.precise-revelation") else 0.04
    accuracy = (accuracy_per_stack * stacks) + studied_accuracy
    state["active_revelation_payoff"] = {
        "target_key": target_key,
        "stacks": stacks,
        "accuracy": accuracy,
        "resolved": False,
    }
    return (
        accuracy,
        1.0 + (0.05 * stacks),
        (f"{character.name} commits {stacks} Revelation to reading {target.name}.\n"),
    )


def finish_revelation_payoff(character: Any, target: Any, *, hit: bool) -> str:
    """Apply a successful Revelation pressure rider once per action."""
    state = combat_state(character)
    active = state.get("active_revelation_payoff")
    if not isinstance(active, dict) or active.get("target_key") != _target_key(target):
        return ""
    if active.get("resolved"):
        return ""
    active["resolved"] = True
    stacks = max(0, int(active.get("stacks", 0) or 0))
    if not hit:
        if stacks and _has_track_talent(character, "seeker.conserved-insight"):
            add_revelation(character, target, 1, "conserved insight")
            return f"{character.name} conserves one Revelation despite the miss.\n"
        return f"{character.name}'s committed Revelation is lost on the miss.\n"
    defense = getattr(target, "stat_effects", {}).get("Defense")
    if defense is not None:
        existing = int(defense.extra or 0) if defense.active else 0
        defense.active = True
        exposed_truth = _has_track_talent(character, "seeker.exposed-truth")
        severity = 2 if exposed_truth else 1
        duration = 3 if exposed_truth else 2
        defense.duration = max(int(defense.duration or 0), duration)
        defense.extra = max(-20, min(-(severity * stacks), existing - (severity * stacks)))
    return f"Revelation exposes {target.name}, deepening the opening.\n"


def case_progress(character: Any, target_or_type: Any) -> int:
    """Return journal progress for a target or broad enemy-type value."""
    enemy_type = getattr(target_or_type, "enemy_typ", target_or_type)
    if not enemy_type:
        return 0
    return int(ensure_state(character)["case_journal"].get(str(enemy_type), 0) or 0)


def _ring_insight_bonus(character: Any, target: Any, reason: str) -> str:
    state = combat_state(character)
    if state.get("seeker_insight_smoothed") or not _ring_awakened_equipped(character, "Seeker"):
        return ""
    state["seeker_insight_smoothed"] = True
    return add_revelation(character, target, 1, f"Hidden Cache insight after {reason}")


def record_inspect(character: Any, target: Any) -> str:
    """Record a committed Inspect and apply studied/ring insight bonuses."""
    if target is None or class_name(character) not in {"Inquisitor", "Seeker"}:
        return ""
    msg = add_revelation(character, target, 1, "Inspect")
    enemy_type = str(getattr(target, "enemy_typ", "") or "")
    state = combat_state(character)
    if case_progress(character, enemy_type) >= 25 and not state.get("inspect_studied_bonus_used"):
        state["inspect_studied_bonus_used"] = True
        msg += add_revelation(character, target, 1, "a familiar tell")
    msg += _ring_insight_bonus(character, target, "Inspect")
    amount = 4 if _has_track_talent(character, "seeker.practiced-inspection") else 3
    msg += gain_case_progress(character, enemy_type, amount, "Inspect")
    return msg


def record_investigation_setup(character: Any, target: Any, action: str, success: bool) -> str:
    """Grant insight after a successful authored anti-magic/setup action."""
    if not success or action not in INVESTIGATION_SETUP_ACTIONS:
        return ""
    return add_revelation(character, target, 1, action)


def record_visible_telegraph(
    character: Any,
    target: Any,
    *,
    visible: bool,
) -> str:
    """Record one visible charged-action read and arm studied prediction."""
    if not visible or target is None or class_name(character) not in {"Inquisitor", "Seeker"}:
        return ""
    state = combat_state(character)
    token = int(state.get("incoming_action_token", 0) or 0)
    claim = (_target_key(target), token)
    reads = state.setdefault("telegraph_reads", set())
    if claim in reads:
        return ""
    reads.add(claim)
    msg = add_revelation(character, target, 1, "a visible tell")
    msg += _ring_insight_bonus(character, target, "the read")
    msg += gain_case_progress(character, getattr(target, "enemy_typ", None), 1, "a visible tell")
    if case_progress(character, target) >= 75:
        state.setdefault("pending_case_prediction", {})[_target_key(target)] = 0.10
        msg += f"{character.name} anticipates {target.name}'s follow-through.\n"
    return msg


def begin_case_prediction(character: Any, actor: Any) -> None:
    """Arm a Pattern Lock dodge bonus for this enemy's next action."""
    state = combat_state(character)
    pending = state.setdefault("pending_case_prediction", {})
    state["active_case_prediction"] = pending.pop(_target_key(actor), None)


def case_prediction_dodge_bonus(character: Any, attacker: Any) -> float:
    """Return the active studied prediction bonus for the current action."""
    del attacker
    return max(0.0, float(combat_state(character).get("active_case_prediction") or 0.0))


def gain_case_progress(character: Any, enemy_type: Any, amount: int, reason: str) -> str:
    if class_name(character) not in {"Inquisitor", "Seeker"} or not enemy_type:
        return ""
    state = ensure_state(character)
    key = str(enemy_type)
    before = int(state["case_journal"].get(key, 0) or 0)
    after = min(100, before + max(0, int(amount)))
    state["case_journal"][key] = after
    state["case_focus"] = key
    if after == before:
        return ""
    crossed = next(
        (name for threshold, name in CASE_MILESTONES if before < threshold <= after),
        None,
    )
    if crossed:
        return f"Case Journal insight deepens for {key}: {crossed}.\n"
    return f"Case Journal gathers evidence about {key} from {reason}.\n"


def case_rank(progress: int) -> str:
    for threshold, name in CASE_MILESTONES:
        if int(progress or 0) >= threshold:
            return name
    return "Unstudied"


def wayfinding_discount(
    character: Any,
    *,
    enemy_type: Any | None = None,
    mapping_progress: float | None = None,
) -> float:
    if class_name(character) != "Seeker":
        return 0.0
    route_type = enemy_type or ensure_state(character).get("case_focus")
    progress = case_progress(character, route_type) if route_type else 0
    discount = 0.10 if progress >= 100 else 0.0
    mapping_threshold = 0.35 if _has_track_talent(character, "seeker.early-bearings") else 0.50
    if mapping_progress is not None and float(mapping_progress) >= mapping_threshold:
        discount = max(discount, 0.05)
    if discount and _has_track_talent(character, "seeker.efficient-passage"):
        discount += 0.05
    if _ring_awakened_equipped(character, "Seeker"):
        discount += 0.05
    return min(0.20, discount)


def wayfinding_cost(character: Any, base_cost: int, **context: Any) -> tuple[int, str]:
    """Return a Seeker movement spell's context-sensitive MP cost."""
    discount = wayfinding_discount(character, **context)
    cost = max(0, int(round(int(base_cost) * (1.0 - discount))))
    if cost == int(base_cost):
        return cost, ""
    return cost, f"Wayfinding finds a steadier route, saving {int(base_cost) - cost} MP.\n"


def level_mapping_progress(character: Any, dungeon_level: int | None = None) -> float:
    """Return the explored fraction of one loaded dungeon level."""
    level = int(getattr(character, "location_z", 0) if dungeon_level is None else dungeon_level)
    tiles = [
        tile
        for position, tile in getattr(character, "world_dict", {}).items()
        if len(position) >= 3 and int(position[2]) == level
    ]
    if not tiles:
        return 0.0
    mapped = sum(
        bool(getattr(tile, "visited", False) or getattr(tile, "near", False)) for tile in tiles
    )
    return mapped / len(tiles)


def gain_stolen_charge(character: Any, reason: str) -> str:
    amount = 1
    if reason == "stolen spell scroll":
        try:
            from ...progression import has_talent

            if has_talent(character, "spell-stealer.counterfeit-casting"):
                amount = 2
        except (AttributeError, KeyError, TypeError, ValueError):
            pass
    return gain_meter(character, "stolen_charge", amount, reason)


def devotion_guard_reduction(character: Any, damage: int) -> tuple[int, str]:
    """Apply held Devotion's passive incoming-damage reduction."""
    if damage <= 0 or class_name(character) not in {"Cleric", "Templar", "Hierophant"}:
        return damage, ""
    stacks = min(
        cap_for(character, "devotion"),
        max(0, int(combat_state(character).get("devotion", 0) or 0)),
    )
    if stacks <= 0:
        return damage, ""
    from ..cleric import has_cleric_talent

    per_stack = 0.03
    if has_cleric_talent(character, "cleric.held-faith"):
        per_stack += 0.01
    if has_cleric_talent(character, "hierophant.warded-faith"):
        per_stack += 0.01
    reduced = int(damage * (per_stack * stacks))
    if reduced <= 0:
        return damage, ""
    damage = max(0, damage - reduced)
    return damage, f"{character.name}'s Devotion guard reduces damage by {reduced}.\n"


def combat_skill_visible(character: Any, skill: Any) -> bool:
    """Return whether a promotion-kit skill should be visible in combat menus."""
    name = str(getattr(skill, "name", "") or "")
    if name == "Sanctuary Ward":
        return int(combat_state(character).get("devotion", 0) or 0) > 0
    from .resolve import RESOLVE_SURGES, resolve_surge_available

    if name in {entry["name"] for entry in RESOLVE_SURGES}:
        return resolve_surge_available(character, name)
    return True


def sanctuary_ward(character: Any) -> str:
    if class_name(character) not in {"Cleric", "Templar", "Hierophant"}:
        return "Sanctuary Ward belongs to the Cleric, Templar, and Hierophant track.\n"
    stacks = int(combat_state(character).get("devotion", 0) or 0)
    if stacks <= 0:
        return "Sanctuary Ward requires Devotion.\n"
    if not _spend_mp(character, 8):
        return "Not enough MP for Sanctuary Ward.\n"
    spent = spend_meter(character, "devotion")
    effect = character.magic_effects["Nature Shield"]
    effect.active = True
    from ..cleric import has_cleric_talent

    effect.duration = 3 if has_cleric_talent(character, "cleric.lasting-sanctuary") else 2
    effect.extra = max(10, spent * 12)
    msg = f"{character.name} spends {spent} Devotion on Sanctuary Ward.\n"
    if spent >= 3:
        cleansed = _cleanse_one_hostile_status(character)
        if cleansed:
            msg += f"Sanctuary Ward cleanses {cleansed}.\n"
    if spent >= 4:
        regen = character.magic_effects["Regen"]
        regen.active = True
        regen.duration = max(regen.duration, 2)
        regen.extra = max(int(regen.extra or 0), spent * 4)
        msg += "Sanctuary Ward kindles restorative light.\n"
    msg += _apply_ordered_blessing(character, spent)
    return _preserve_spent_meter(character, "devotion", "Templar", "Ordered Blessings", msg)


def relic_aegis(character: Any) -> str:
    if class_name(character) != "Templar":
        return "Relic Aegis requires Templar training.\n"
    if getattr(character.equipment.get("OffHand"), "subtyp", None) != "Shield":
        return "Relic Aegis requires a shield.\n"
    stacks = int(combat_state(character).get("devotion", 0) or 0)
    if stacks < 2:
        return "Relic Aegis requires at least 2 Devotion.\n"
    if not _spend_mp(character, 12):
        return "Not enough MP for Relic Aegis.\n"
    spent = spend_meter(character, "devotion")
    from ..cleric import has_cleric_talent

    relic_scale = 1.25 if has_cleric_talent(character, "templar.reinforced-relic") else 1.0
    if has_cleric_talent(character, "templar.unbroken-reliquary") and int(
        character.health.current
    ) * 2 < int(character.health.max):
        relic_scale *= 1.25
    extra_turn = int(has_cleric_talent(character, "templar.enduring-aegis"))
    effect = character.magic_effects["Nature Shield"]
    effect.active = True
    effect.duration = 3 + extra_turn
    effect.extra = max(20, int(spent * 18 * relic_scale))
    msg = f"{character.name} spends {spent} Devotion on Relic Aegis.\n"
    empowered = _power_up_active(character, "Holy Retribution")
    combat_state(character)["relic_aegis_counter"] = {
        "damage": max(
            1,
            int(4 * spent * (1.5 if empowered else 1.0) * relic_scale),
        ),
        "turns": (4 if empowered else 3) + extra_turn,
    }
    msg += "Relic Aegis readies a holy counter.\n"
    msg += _apply_ordered_blessing(character, spent)
    return _preserve_spent_meter(character, "devotion", "Templar", "Ordered Blessings", msg)


def resolve_devotion_counter(character: Any, attacker: Any, damage: int) -> str:
    """Resolve one armed Templar counter after a positive incoming weapon hit."""
    if damage <= 0 or attacker is None or class_name(character) != "Templar":
        return ""
    from ...combat.reactions import execute_reaction

    def resolve() -> str:
        state = combat_state(character)
        total = 0
        labels: list[str] = []
        for key, label in (
            ("relic_aegis_counter", "Relic Aegis"),
            ("ordered_blessing_counter", "Ordered Blessings"),
        ):
            counter = state.get(key)
            if isinstance(counter, dict) and int(counter.get("turns", 0) or 0) > 0:
                total += max(0, int(counter.get("damage", 0) or 0))
                labels.append(label)
                state[key] = None
        if total <= 0:
            return ""
        _hit, reduction, dealt = attacker.damage_reduction(total, character, typ="Holy")
        dealt = max(0, min(int(dealt or 0), attacker.health.current))
        if dealt:
            attacker.health.current -= dealt
            character._emit_damage_event(
                attacker,
                dealt,
                damage_type="Holy",
                source="promotion_kit_payoff",
                ability_name=" / ".join(labels),
            )
        return reduction + f"{' and '.join(labels)} return {dealt} Holy damage.\n"

    return execute_reaction("devotion_counter", character, resolve) or ""


def consecrated_conduit(character: Any) -> str:
    if class_name(character) != "Hierophant":
        return "Consecrated Conduit requires Hierophant training.\n"
    weapon = getattr(character, "equipment", {}).get("Weapon")
    if getattr(weapon, "subtyp", None) != "Staff":
        return "Consecrated Conduit requires a staff.\n"
    stacks = int(combat_state(character).get("devotion", 0) or 0)
    if stacks <= 0:
        return "Consecrated Conduit requires Devotion.\n"
    if not _spend_mp(character, 10):
        return "Not enough MP for Consecrated Conduit.\n"
    spent = spend_meter(character, "devotion")
    combat_state(character)["consecrated_conduit"] = {"stacks": spent}
    return f"{character.name} spends {spent} Devotion on Consecrated Conduit.\n"


def supplication(character: Any, target: Any | None = None) -> str:
    if class_name(character) not in {"Priest", "Archbishop"}:
        return "Supplication belongs to the Priest and Archbishop track.\n"
    stacks = int(combat_state(character).get("prayer", 0) or 0)
    if stacks <= 0:
        return "Supplication requires Prayer.\n"
    target = target or character
    if not getattr(target, "is_alive", lambda: True)():
        return "Supplication requires a living target.\n"
    if not _spend_mp(character, 10):
        return "Not enough MP for Supplication.\n"
    spent = spend_meter(character, "prayer")
    gospel = _power_up_active(character, "Great Gospel")
    scale = 1.20 if gospel else 1.0
    if _has_track_talent(character, "priest.fervent-supplication"):
        scale += 0.15
    if _has_track_talent(character, "archbishop.abundant-mercy"):
        scale += 0.20
    heal = min(
        target.health.max - target.health.current,
        max(1, int((12 * spent + character.stats.wisdom // 2) * scale)),
    )
    target.health.current += heal
    msg = f"{character.name} spends {spent} Prayer; Supplication restores {heal} HP.\n"
    ward = target.magic_effects["Nature Shield"]
    ward.active = True
    ward_duration = 3 if gospel else 2
    if _has_track_talent(character, "priest.sheltering-prayer"):
        ward_duration += 1
    ward.duration = max(ward.duration, ward_duration)
    ward_scale = 8 if _has_track_talent(character, "archbishop.sheltering-word") else 6
    ward.extra = max(int(ward.extra or 0), int(ward_scale * spent * scale))
    cleanse_chance = 0.10 * spent
    if _has_track_talent(character, "priest.merciful-prayer"):
        cleanse_chance += 0.15
    if _has_track_talent(character, "archbishop.purifying-word"):
        cleanse_chance += 0.20
    if random.random() < min(0.90, cleanse_chance):
        cleansed = _cleanse_one_hostile_status(target)
        if cleansed:
            msg += f"Supplication cleanses {cleansed}.\n"
    msg = _preserve_spent_meter(character, "prayer", "Archbishop", "Divine Intervention", msg)
    if _has_track_talent(character, "archbishop.endless-supplication"):
        msg += gain_meter(character, "prayer", 1, "Endless Supplication")
    return msg


def great_benediction(character: Any) -> str:
    if class_name(character) != "Archbishop":
        return "Great Benediction requires Archbishop training.\n"
    stacks = int(combat_state(character).get("prayer", 0) or 0)
    minimum = 2 if _has_track_talent(character, "archbishop.ready-benediction") else 3
    if stacks < minimum:
        return f"Great Benediction requires at least {minimum} Prayer.\n"
    if not _spend_mp(character, 18):
        return "Not enough MP for Great Benediction.\n"
    spent = spend_meter(character, "prayer")
    gospel = _power_up_active(character, "Great Gospel")
    scale = 1.20 if gospel else 1.0
    if _has_track_talent(character, "archbishop.greater-benediction"):
        scale += 0.15
    duration = 5 if gospel else 4
    if _has_track_talent(character, "archbishop.lasting-benediction"):
        duration += 1
    character.stat_effects["Magic Defense"].active = True
    character.stat_effects["Magic Defense"].duration = duration
    defense_scale = 5 if _has_track_talent(character, "archbishop.benediction-aegis") else 4
    character.stat_effects["Magic Defense"].extra = max(
        int(character.stat_effects["Magic Defense"].extra or 0), int(spent * defense_scale * scale)
    )
    character.magic_effects["Regen"].active = True
    character.magic_effects["Regen"].duration = duration
    character.magic_effects["Regen"].extra = max(
        int(character.magic_effects["Regen"].extra or 0), int(spent * 5 * scale)
    )
    combat_state(character)["great_benediction"] = {
        "turns": duration,
        "healing": (0.05 if _has_track_talent(character, "archbishop.healing-liturgy") else 0.04)
        * spent
        * scale,
        "reduction": (
            0.025 if _has_track_talent(character, "archbishop.protective-liturgy") else 0.02
        )
        * spent
        * scale,
        "status": (
            0.07 if _has_track_talent(character, "archbishop.unshaken-congregation") else 0.05
        )
        * spent
        * scale,
        "mana": int(
            math.ceil(spent / (2 if _has_track_talent(character, "archbishop.mana-liturgy") else 3))
        ),
    }
    msg = f"{character.name} spends {spent} Prayer on Great Benediction.\n"
    return _preserve_spent_meter(character, "prayer", "Archbishop", "Divine Intervention", msg)


def great_gospel_prayer(character: Any) -> str:
    if class_name(character) != "Archbishop":
        return ""
    cap = cap_for(character, "prayer")
    state = combat_state(character)
    fraction = 0.75 if _has_track_talent(character, "archbishop.opening-gospel") else 0.50
    state["prayer"] = max(int(state.get("prayer", 0) or 0), int(math.ceil(cap * fraction)))
    return f"Great Gospel raises Prayer to {state['prayer']}/{cap}.\n"


def benediction_healing_multiplier(character: Any) -> float:
    payload = combat_state(character).get("great_benediction")
    if not isinstance(payload, dict) or int(payload.get("turns", 0) or 0) <= 0:
        return 1.0
    return 1.0 + max(0.0, float(payload.get("healing", 0.0) or 0.0))


def benediction_status_multiplier(character: Any) -> float:
    payload = combat_state(character).get("great_benediction")
    if not isinstance(payload, dict) or int(payload.get("turns", 0) or 0) <= 0:
        return 1.0
    return 1.0 + max(0.0, float(payload.get("status", 0.0) or 0.0))


def benediction_damage_reduction(character: Any, damage: int) -> tuple[int, str]:
    payload = combat_state(character).get("great_benediction")
    if damage <= 0 or not isinstance(payload, dict) or int(payload.get("turns", 0) or 0) <= 0:
        return damage, ""
    reduced = max(0, int(damage * float(payload.get("reduction", 0.0) or 0.0)))
    if reduced <= 0:
        return damage, ""
    return max(0, damage - reduced), f"Great Benediction prevents {reduced} damage.\n"


def record_magical_invigoration_tick(character: Any) -> str:
    """Add one independently expiring Magic stack after a Regen tick."""
    if not _has_skill(character, "Magical Invigoration"):
        return ""
    state = combat_state(character)
    stacks = state.setdefault("magical_invigoration", [])
    if not isinstance(stacks, list):
        stacks = []
        state["magical_invigoration"] = stacks
    duration = 4 if _has_track_talent(character, "archbishop.enduring-invigoration") else 3
    if _has_track_talent(character, "priest.long-regeneration"):
        duration += 1
    stacks.append(duration)
    return f"{character.name} gains Magical Invigoration ({len(stacks)} stacks).\n"


def tick_magical_invigoration(character: Any) -> None:
    """Advance separately timed Magical Invigoration stacks."""
    state = combat_state(character)
    stacks = state.get("magical_invigoration")
    if not isinstance(stacks, list):
        return
    state["magical_invigoration"] = [int(turns) - 1 for turns in stacks if int(turns) > 1]


def magical_invigoration_bonus(character: Any) -> int:
    """Return the current Magic rating supplied by Regen-derived stacks."""
    stacks = combat_state(character).get("magical_invigoration", [])
    if not isinstance(stacks, list):
        return 0
    amount = 4
    if _has_track_talent(character, "priest.arcane-renewal"):
        amount += 2
    if _has_track_talent(character, "archbishop.radiant-renewal"):
        amount += 2
    return len(stacks) * amount


def begin_ki_spender(character: Any, ability_name: str) -> str:
    """Spend one Ki for an authored rider after ordinary validation."""
    state = combat_state(character)
    state["ki_spender"] = None
    if (
        class_name(character) not in {"Monk", "Master Monk"}
        or ability_name not in KI_SPEND_ABILITIES
        or int(state.get("ki", 0) or 0) <= 0
    ):
        return ""
    state["ki"] = int(state.get("ki", 0) or 0) - 1
    state["ki_spender"] = ability_name
    return f"{character.name} spends 1 Ki on {ability_name}.\n"


def ki_spender_active(character: Any, ability_name: str) -> bool:
    """Return whether the current action paid for its authored Ki rider."""
    return combat_state(character).get("ki_spender") == ability_name


def finish_ki_spender(
    character: Any,
    target: Any | None,
    ability_name: str,
    *,
    hit: bool = False,
    healing: int = 0,
) -> str:
    """Apply post-resolution Ki riders and clear the one-action context."""
    state = combat_state(character)
    if state.get("ki_spender") != ability_name:
        return ""
    state["ki_spender"] = None
    msg = ""
    if ability_name == "Chi Heal":
        ratio = 0.30 if _has_track_talent(character, "monk.deep-restoration") else 0.20
        if _has_track_talent(character, "master-monk.perfected-restoration"):
            ratio += 0.15
        bonus = min(
            max(0, int(character.health.max) - int(character.health.current)),
            max(0, int(healing * ratio)),
        )
        if bonus:
            character.health.current += bonus
            msg += f"Focused Ki restores {bonus} additional HP.\n"
        immunity = 2 if _has_track_talent(character, "monk.purifying-flow") else 1
        if _has_track_talent(character, "master-monk.purity-without-end"):
            immunity += 1
        state["purge_immunity_turns"] = max(
            immunity,
            int(state.get("purge_immunity_turns", 0) or 0),
        )
        msg += "Focused Ki guards against hostile status for one turn.\n"
    elif ability_name == "Hadouken" and hit and target is not None and target.is_alive():
        effect = target.stat_effects["Magic Defense"]
        effect.active = True
        effect.duration = max(int(effect.duration or 0), 2)
        effect.extra = min(int(effect.extra or 0), -10)
        msg += f"Hadouken lowers {target.name}'s Magic Defense by 10 for two turns.\n"
    return msg


def ki_accuracy_bonus(character: Any, ability_name: str) -> float:
    """Return the paid Ki rider's per-strike accuracy bonus."""
    if ki_spender_active(character, ability_name) and ability_name == "Hyakuretsukyaku":
        return 0.15 if _has_track_talent(character, "master-monk.hundredfold-precision") else 0.10
    return 0.0


def ki_control_bonus(character: Any, ability_name: str) -> float:
    """Return the paid Ki rider's control-contest bonus."""
    if ki_spender_active(character, ability_name) and ability_name in {"Leg Sweep", "Suplex"}:
        return 0.25 if _has_track_talent(character, "master-monk.perfect-control") else 0.15
    return 0.0


def record_ki_martial_hit(character: Any, metadata: dict[str, Any] | None) -> str:
    """Grant ordinary martial rhythm once for the current player action."""
    if class_name(character) not in {"Monk", "Master Monk"}:
        return ""
    metadata = metadata or {}
    state = combat_state(character)
    ability_name = str(
        metadata.get("ability_name")
        or state.get("action_choice")
        or ("Attack" if state.get("action_name") == "Attack" else "")
    )
    if ability_name == "Dim Mak":
        return ""
    weapon_type = str(metadata.get("weapon_type") or "")
    weapon_name = str(metadata.get("weapon_name") or "")
    basic = not ability_name or ability_name == "Attack"
    if basic:
        qualifies = weapon_type in {"Fist", "None"} or weapon_name == "Ruyi Jingu Bang"
    else:
        qualifies = ability_name in MARTIAL_KI_ACTIONS
    if not qualifies:
        return ""
    token = int(state.get("action_token", 0) or 0)
    if token > 0 and state.get("ki_action_token") == token:
        return ""
    state["ki_action_token"] = token if token > 0 else -1
    amount = 1
    if int(state.get("ki", 0) or 0) == 0 and _has_track_talent(
        character, "monk.rhythmic-breathing"
    ):
        amount += 1
    return gain_meter(character, "ki", amount, "martial hit")


def begin_incoming_ki_action(character: Any) -> None:
    """Open one defensive-reaction Ki claim for an incoming hostile action."""
    state = combat_state(character)
    state["ki_reaction_token"] = int(state.get("ki_reaction_token", 0) or 0) + 1


def record_ki_reaction(character: Any, reason: str) -> str:
    """Grant Ki once for a successful dodge, parry, or counter reaction."""
    if class_name(character) not in {"Monk", "Master Monk"}:
        return ""
    state = combat_state(character)
    token = int(state.get("ki_reaction_token", 0) or 0)
    if token and state.get("ki_reaction_claimed") == token:
        return ""
    state["ki_reaction_claimed"] = token
    amount = 1
    if _has_track_talent(character, "monk.reactive-center"):
        amount += 1
    if _has_track_talent(character, "master-monk.rooted-recovery"):
        amount += 1
    return gain_meter(character, "ki", amount, reason)


def rope_a_dope_dodge_bonus(character: Any) -> float:
    """Return the escalating avoidance bonus of an active Rope-a-Dope."""
    payload = combat_state(character).get("rope_a_dope")
    if not isinstance(payload, dict) or not payload.get("active"):
        return 0.0
    base = 0.15 if _has_track_talent(character, "master-monk.slip-the-rope") else 0.10
    step = 0.07 if _has_track_talent(character, "master-monk.rolling-shoulders") else 0.05
    return base + step * max(0, int(payload.get("dodges", 0) or 0))


def record_rope_a_dope_dodge(character: Any, attacker: Any) -> str:
    """Advance Rope-a-Dope and release its four-hit answer at three dodges."""
    payload = combat_state(character).get("rope_a_dope")
    if not isinstance(payload, dict) or not payload.get("active"):
        return ""
    if payload.get("target") is not attacker:
        return ""
    payload["dodges"] = int(payload.get("dodges", 0) or 0) + 1
    if payload["dodges"] < 3:
        return f"Rope-a-Dope rises to {payload['dodges']} consecutive dodges.\n"
    payload["active"] = False
    modifiers = (0.40, 0.50, 0.60, 0.70)
    if _has_track_talent(character, "master-monk.championship-round"):
        modifiers = (0.50, 0.60, 0.70, 0.80)
    msg = f"{character.name} answers with the Rope-a-Dope combination!\n"
    for modifier in modifiers:
        hit_message, _hit, _critical = character.weapon_damage(
            attacker,
            dmg_mod=modifier,
            use_offhand=False,
        )
        msg += hit_message
        if not attacker.is_alive():
            break
    if _has_track_talent(character, "master-monk.second-wind"):
        healing = min(
            character.health.max - character.health.current,
            max(1, int(character.health.max * 0.10)),
        )
        character.health.current += healing
        msg += f"Second Wind restores {healing} HP.\n"
    return msg


def break_rope_a_dope(character: Any) -> str:
    """End Rope-a-Dope when its user takes damage."""
    payload = combat_state(character).get("rope_a_dope")
    if not isinstance(payload, dict) or not payload.get("active"):
        return ""
    payload["active"] = False
    return f"{character.name}'s Rope-a-Dope stance breaks on the hit.\n"


def dim_mak(character: Any, target: Any | None) -> str:
    if class_name(character) != "Master Monk":
        return "Dim Mak requires Master Monk training.\n"
    cap = cap_for(character, "ki")
    if int(combat_state(character).get("ki", 0) or 0) < cap:
        return "Dim Mak requires full Ki.\n"
    if target is None:
        return "There is no target for Dim Mak.\n"
    if not target.is_alive():
        return "Dim Mak requires a living target.\n"
    weapon = character.equipment.get("Weapon")
    subtyp = getattr(weapon, "subtyp", None)
    weapon_name = getattr(weapon, "name", "")
    if subtyp not in {"Fist", "Staff", "None"}:
        return "Dim Mak requires an empty hand, fist weapon, or staff.\n"
    if not _spend_mp(character, 18):
        return "Not enough MP for Dim Mak.\n"
    spent = spend_meter(character, "ki")
    penalty = 1.0
    drop_msg = ""
    if subtyp == "Fist":
        penalty = 0.90
    elif subtyp == "Staff" and weapon_name == "Ruyi Jingu Bang":
        penalty = 1.0
    elif subtyp == "Staff":
        from ... import items

        penalty = 0.90 if _has_track_talent(character, "master-monk.flexible-form") else 0.80
        drop_msg = "The ordinary staff cannot hold the finisher and is disarmed.\n"
        if hasattr(character, "modify_inventory"):
            character.modify_inventory(weapon, 1)
        character.equipment["Weapon"] = items.NoWeapon()
    hp_before = int(target.health.current)
    ring = _ring_awakened_equipped(character, "Master Monk")
    damage_per_ki = 0.15 if _has_track_talent(character, "master-monk.decisive-pressure") else 0.12
    accuracy = 0.10 if ring else 0.0
    if _has_track_talent(character, "master-monk.death-point-focus"):
        accuracy += 0.10
    attack_msg, hit, _crit = character.weapon_damage(
        target,
        dmg_mod=(1.5 + spent * damage_per_ki) * penalty,
        use_offhand=False,
        accuracy_modifier=accuracy,
    )
    damage = max(0, hp_before - int(target.health.current))
    msg = f"{character.name} spends {spent} Ki on Dim Mak.\n{attack_msg}{drop_msg}"
    if hit and target.is_alive():
        killed, _immune = resolve_death_contest(
            character,
            target,
            actor_roll_multiplier=1.10 if ring else 1.0,
        )
        if killed:
            msg += f"Dim Mak extinguishes {target.name}'s life force.\n"
        elif not target.has_status_protection("Stun"):
            actor_roll = random.randint(0, max(1, character.stats.wisdom))
            if ring:
                actor_roll = int(actor_roll * 1.10)
            defender_roll = random.randint(0, max(1, target.stats.con))
            if target.stun_contest_success(character, actor_roll, defender_roll):
                if target.apply_stun(2, source="Dim Mak", applier=character):
                    msg += f"{target.name} is stunned by the disrupted chi.\n"
    if hit and not target.is_alive():
        recovery_scale = (
            1.25 if _has_track_talent(character, "master-monk.essence-mastery") else 1.0
        )
        character.health.current = min(
            character.health.max,
            character.health.current + int(target.health.max * recovery_scale),
        )
        character.mana.current = min(
            character.mana.max,
            character.mana.current + int(target.mana.max * recovery_scale),
        )
        msg += f"{character.name} absorbs {target.name}'s essence.\n"
    state = combat_state(character)
    refund_training = _has_track_talent(character, "master-monk.inner-reserve")
    if (
        (ring or refund_training)
        and hit
        and damage > 0
        and not state.get("martial_master_refund_used")
    ):
        state["martial_master_refund_used"] = True
        refund = 2 if _has_track_talent(character, "master-monk.perfect-recovery") else 1
        state["ki"] = refund
        msg += f"Martial Master refunds {refund} Ki after the clean finisher.\n"
    return msg
