"""Class progression skill and spell catalogs."""

from __future__ import annotations

from functools import lru_cache

from .assassin import (
    ApplyToxin,
    BlackLotusMastery,
    CoatingConservation,
    Cutthroat,
    DeathSentence,
    Disembowel,
    Distract,
    ExecutionRhythm,
    FindTraps,
    ForGoodMeasure,
    GhostStep,
    HiddenBlade,
    LingeringVenom,
    LiveAndLearn,
    MainGauche,
    MakeToxin,
    MarkedShuriken,
    OffHandExcellence,
    Potentiation,
    ResistDeath,
    ShadowCounter,
    ShadowEvasion,
    SilentWalking,
    SmashAndGrab,
    Surprise,
    ThousandCuts,
    ToxicPrecision,
    TwistTheKnife,
    Untouchable,
)
from .bard import (
    Countermelody,
    CurtainGuard,
    DissonantChord,
    InspiringVerse,
    PrismaticFinale,
    PrismaticRay,
    RallyingChorus,
    ResonantWave,
    RhythmicStrike,
    SyncopatedStrike,
)
from .base import (
    CallContract,
)
from .cleric import (
    BastionPrayer,
    ConduitStrike,
    DevotionalRebuke,
    GracefulIntercession,
    HallowedReadiness,
    SacredMending,
)
from .defender import (
    BattleDetermination,
    Boast,
    BulwarkGuard,
    CriticalVigor,
    CrushingVengeance,
    DoublePayback,
    Dragonheart,
    DragonSoul,
    ExtendedReach,
    FocusedAssault,
    GeneratorShield,
    GetEven,
    IronMaiden,
    Phalanx,
    PurgeWeakness,
    Repercussion,
    ShieldRiposte,
    SpellBlock,
    SpellReflection,
    Stronghold,
    SwingAndBash,
    TowerOffense,
    VigilantLanding,
)
from .detection import (
    DetectAnimal,
    DetectElemental,
    DetectFiend,
    DetectHumanoid,
    DetectSlime,
    DetectUndead,
)
from .enemy import Counterspell, DazedOrConfused, NightmareFuel
from .healer import (
    BeginnersLuck,
    Cacophany,
    Courage,
    DelayedReaction,
    FlashBlindness,
    IncitePanic,
    Lullaby,
    Meditation,
    MentalShard,
    Safeguarding,
    StaffProficiency,
    Tranquility,
    Tutelary,
    Vision,
    ZenAccuracy,
)
from .healer_promotions import (
    FlowingPalm,
    MagicalInvigoration,
    RopeADope,
    UnarmedProficiency,
)
from .inquisitor import (
    DeductiveStrike,
    ForegoneConclusion,
    SafePassage,
    SurveyorsStep,
    TakeNotes,
)
from .knight_enchanter import (
    AegisWeave,
    ArcaneRiposte,
    CleavingEdge,
    DefensiveRelease,
    EchoingBlade,
    QuickRecharge,
    ReDebuff,
    ResonantStrike,
    Spellbind,
    StorageCapacity2,
    WeaveReservoir,
)
from .mage import (
    Aftershock,
    ArcaneEmpowerment,
    ArcaneRitual,
    ArcaneTradition,
    Aspirate,
    Banish,
    BarrierWall,
    ClassicalEnrichment,
    ClassicalForce,
    Combustion,
    ConjureAnimal,
    ConjureBlade,
    ConjureCelestial,
    ConjureDragon,
    ConjureElixir,
    ConjureFiend,
    ConjureHumanoid,
    ConjureMonster,
    ConjurePotion,
    ConjureShackles,
    ConjureSpirit,
    DetonationCascade,
    DivineWind,
    EjectionGale,
    ElectricalBurns,
    Electrified,
    ElementalConvergence,
    EnlivenDead,
    ExplosiveDecoy,
    FireInside,
    FloatingCrystal,
    ForceMultiplier,
    Fragmentation,
    FrozenArmor,
    GravitationalPull,
    IllusoryLink,
    Inferno,
    InflateHealth,
    ManaBarbs,
    ManaLeak,
    ManaRupture,
    ManaSplinters,
    MiracleBlade,
    MiracleCrystal,
    MiraclePotion,
    MiracleShackles,
    Multiplicity,
    Paralyzer,
    Polymorph,
    PrismaticCataclysm,
    Refreshment,
    Refueling,
    Slow,
    Snowpiercer,
    Spaghettification,
    Subzero,
    TerraFirma,
    Torchlight,
    UnrelentingWaves,
    UnsteadyGround,
    WindCurrents,
)
from .pathfinder import (
    AccessStorage,
    BounceBack,
    CallAnimal,
    CautiousAssault,
    CenterBeast,
    Chronology,
    ControlZ,
    Conversion,
    CreatureComforts,
    DragonFang,
    FundamentalHarmony,
    Geomancy,
    GrovePulse,
    IntensifyElements,
    LunarRend,
    NoxiousMist,
    NullifyPoison,
    PoisonStrike,
    PrimalPractice,
    PrimalTrance,
    RayOfMoonlight,
    RazorTalons,
    ResistPoison,
    RestoringBoon,
    SilentLucidity,
    SpiritStrike,
    Starfall,
    TemporaryStasis,
    Tephra,
    ThornyVine,
    UnnaturalPurge,
    VerySuperstitious,
)
from .powerups import (
    AbyssalAuthority,
    Alacrity,
    ControlledCorruption,
    DimMak,
    FinePrint,
    Patronage,
)
from .promotions import (
    BeyondReproach,
    BraceWall,
    Censure,
    CenteredGuard,
    CheatDeath,
    CitadelAegis,
    Condemnation,
    ConduitCommand,
    ConsecratedConduit,
    DeathMark,
    FindersKeepers,
    FourfoldSurge,
    GrandFinale,
    GreatBenediction,
    GuardPartner,
    HarryPrey,
    HoldTheLine,
    InvokeAgloolik,
    InvokeBardi,
    InvokeCacus,
    InvokeCaladrius,
    InvokeDilong,
    InvokeHala,
    InvokeHodag,
    InvokeIzulu,
    InvokeKobalos,
    InvokeLamashtu,
    InvokePatagon,
    InvokeSeraphim,
    InvokeTiamat,
    InvokeZahhak,
    IronwallReprisal,
    LastBastionSurge,
    MartialMastery,
    MendWounds,
    MirrorBreath,
    OathsJudgment,
    OathsShelter,
    PackStrike,
    Penalization,
    PrayerOfFaith,
    PurgingKata,
    RadiantHealing,
    RallyPartner,
    RelicAegis,
    Sanctification,
    SanctuaryWard,
    ScavengersEye,
    ShieldRicochet,
    Supplication,
    ThreadedCast,
    TotemSurge,
    UndeadHunter,
    UnleashInstinct,
    Wayfinding,
    WingedPounce,
)
from .ranger import HuntersSnare, QuarryCleave, UncannyVolley, WildSense
from .shaman import (
    AncestralAegis,
    ResonantWard,
    SoulRend,
    Soulstorm,
    SpiritAnimal,
    SpiritClaw,
    SpiritMend,
)
from .skills import (
    AnvilStrike,
    AnvilStrike2,
    AnvilStrike3,
    BattleCry,
    BlessedLight,
    BlindFighting,
    BoomerangToss,
    Brace,
    Brace2,
    Brace3,
    BrutishStrength,
    Charge,
    ComposedWrath,
    Cripple,
    CrossBlock,
    DevastatingThrow,
    Doublecast,
    DoubleStrike,
    DragonDive,
    DrivingThrust,
    DrunkenBrawler,
    DualWield,
    DualWieldExcellence,
    DualWieldMastery,
    Duelist,
    Fatality,
    FavoredEnemy,
    FinalAssault,
    FlurryBlades,
    Frenzy,
    GuardCleaver,
    GuardCleaver2,
    GuardCleaver3,
    Hadouken,
    Headbutt,
    Hemorrhage,
    Hemorrhage2,
    Hemorrhage3,
    HemorrhageThirst,
    Hyakuretsukyaku,
    IronPalm,
    IronPalm2,
    IronPalm3,
    Jump,
    LanceSweep,
    LastStand,
    LowSweep,
    LowSweep2,
    LowSweep3,
    Maim,
    Momentum,
    MonkeyGrip,
    MonkeyGrip2,
    MortalStrike,
    MortalStrike2,
    PainTolerance,
    PiercingStrike,
    PolearmExcellence,
    PolearmMastery,
    PolearmProficiency,
    ReaversMark,
    ReaversMark2,
    ReaversMark3,
    RecklessOnslaught,
    Retort,
    RiposteLine,
    RiposteLine2,
    RiposteLine3,
    ShieldBlock,
    ShieldSlam,
    SongRenewal,
    SongShelter,
    SongValor,
    SpinningBackElbow,
    StealAsWell,
    StealSpell,
    StealSpell2,
    Suplex,
    SwordAndBoard,
    TectonicRift,
    ThunderousVault,
    Triplecast,
    TripleStrike,
    TruePiercingStrike,
    TrueStrike,
    TwoHandedWeaponProficiency,
    Uppercut,
    WeaponFocus,
    WeaponSwap,
)
from .spell_stealer import (
    ArcaneAmbush,
    BorrowedWard,
    FalseOpening,
    SpellbreakersCut,
    VanishingAct,
)
from .spell_types import (
    Corruption2,
    EnterWall,
    Foretell,
    HallowedGround,
    Invisibility,
    Nightmare,
    PlantSeeds,
    ResistEarth,
    ResistElectric,
    ResistFire,
    ResistHoly,
    ResistIce,
    ResistShadow,
    ResistWater,
    ResistWind,
    Rewind,
    TwistFate,
    VilePotion,
    Volitation,
    Wormhole,
)
from .spellblade import (
    AmplifyArcane,
    AmplifyElemental,
    Breakdown,
    CounterCharge,
    KineticExplosion,
    NovelShielding,
    StorageCapacity,
)
from .spells import (
    Aqualung,
    AstralShift,
    BallLightning,
    Berserk,
    Bless,
    BlindingFog,
    Bolt,
    Boost,
    CalmingBreeze,
    Cleanse,
    Corruption,
    Desoul,
    Dispel,
    DivineProtection,
    DivineProtection2,
    Doom,
    Earthquake,
    Electrocution,
    Enfeeble,
    Fireball,
    Firebolt,
    Firestorm,
    Gust,
    Haste,
    Heal,
    Heal2,
    Heal3,
    Hex,
    Holy,
    Holy2,
    Holy3,
    Hurricane,
    Hydration,
    IceBlizzard,
    IceBlock,
    IceLance,
    Icicle,
    Kaleidoscope,
    Lightning,
    MagicMissile,
    MagicMissile2,
    MagicMissile3,
    MirrorImage,
    MirrorImage2,
    Mudslide,
    NatureShield,
    Petrify,
    PhotonSphere,
    PoisonBreath,
    PoisonDart,
    Reflect,
    Regen,
    Regen2,
    Regen3,
    Regrowth,
    RepelTheWicked,
    ResistAll,
    Resurrection,
    Sanctuary,
    Scorch,
    ShadowBolt,
    ShadowBolt2,
    ShadowBolt3,
    Shell,
    Shock,
    Silence,
    Sleep,
    Smite,
    Smite2,
    Smite3,
    SoulDrain,
    StoneSkin,
    Teleport,
    Terrify,
    Tornado,
    Tremor,
    Tsunami,
    TurnUndead,
    TurnUndead2,
    Vulcanize,
    WaterJet,
    WeakenMind,
    WindSpeed,
    Windswept,
)
from .thief import (
    AllIn,
    CutAndRun,
    DirtyTrick,
    DisarmTraps,
    PilferingStrike,
    SnakeEyes,
    TakeItOnTheRun,
    TurnTheTables,
)
from .utility import (
    AbsorbEssence,
    AchillesHeel,
    Adrenaline,
    AggressivePursuit,
    AvoidTraps,
    Backstab,
    Cartography,
    Chastise,
    ChiHeal,
    Commitment,
    Cover,
    DefensiveRegen,
    Disarm,
    Dishearten,
    DispelSlash,
    Disruption,
    DoOver,
    ElementalStrike,
    EnhanceArmor,
    EnhanceBlade,
    Evasion,
    EvasiveGuard,
    ExploitWeakness,
    Familiar,
    Familiar2,
    Familiar3,
    Goad,
    GoldToss,
    HealSummon,
    HealthDrain,
    HealthManaDrain,
    HonedAttack,
    ImbueWeapon,
    ImprovedDefend,
    IncantationComprehension,
    Inspect,
    KeenEye,
    KidneyPunch,
    LearnSpell,
    LearnSpell2,
    LegSweep,
    LifeTap,
    Lockpick,
    MaelstromWeapon,
    ManaDepletion,
    ManaDrain,
    ManaShield,
    ManaShield2,
    ManaSlice,
    ManaSlice2,
    ManaTap,
    MasterLockpick,
    Mug,
    MysticalEvasion,
    NaturalAttunement,
    Obscuration,
    Parry,
    PiousBounty,
    PocketSand,
    Posturing,
    PurityBody,
    PurityBody2,
    Quickstep,
    RaiseSummon,
    Rally,
    Retaliate,
    Reveal,
    Riposte,
    Serendipity,
    SleepingPowder,
    SlotMachine,
    SmokeScreen,
    SneakAttack,
    StaffConduit,
    Steal,
    StumbleUpon,
    Tame,
    ThirdEye,
    Totem,
    Transform,
    Transform2,
    Transform3,
    Upsurge,
    Zephyrstrike,
)
from .warlock import (
    Bullionaire,
    ContagiousBlaze,
    ContractKiller,
    CurseDysarthria,
    CurseElijah,
    CurseFrailty,
    CurseSwarms,
    CurseUmbra,
    DanceOfTheDead,
    DeathBecomesUs,
    DemonEyes,
    Eclipse,
    ExpelCurse,
    FamiliarBond,
    FamiliarBond2,
    FesteringAnguish,
    FlammableAffliction,
    GreaseMissile,
    HemorrhagingCurse,
    ImpendingDemise,
    IndiscriminateProvocation,
    InsultToInjury,
    MasterLocator,
    MonkeysPaw,
    MortalShackles,
    MysticalVitality,
    Napalm,
    Netherchar,
    NightMoves,
    NightTerror,
    PennyDreadful,
    PersistentCorruption,
    PiercingBolt,
    ResourceAbuse,
    RestorativeBarrier,
    Sciophobia,
    ShadowCurtain,
    SoulAsylum,
    SoulBinding,
    SoulSiphon,
    SoulVessel,
    ThornByMySide,
    TopOff,
    UnoReverseCard,
    VimAndRigor,
)


def ability_classes_for(entry):
    """Normalize one or more ability classes stored for a single level."""
    if entry is None:
        return []
    if isinstance(entry, (list, tuple)):
        return list(entry)
    return [entry]


def ability_classes_for_level(source: dict, class_name: str, level: int | str):
    return ability_classes_for(source.get(class_name, {}).get(str(level)))


# Parameters
skill_dict = {
    "Warrior": {
        "1": [
            WeaponFocus,
            Rally,
            Adrenaline,
            HonedAttack,
            DrivingThrust,
            ShieldBlock,
            Goad,
            Cripple,
            Dishearten,
            Chastise,
            Commitment,
            Retaliate,
            DoubleStrike,
            ImprovedDefend,
            Upsurge,
            AchillesHeel,
            AggressivePursuit,
        ],
        "3": ShieldSlam,
        "8": PiercingStrike,
        "10": Disarm,
        "15": Charge,
        "23": Parry,
        "25": TrueStrike,
        "28": BattleCry,
    },
    "Weapon Master": {
        "1": [
            DoubleStrike,
            Parry,
            MortalStrike,
            DevastatingThrow,
            TwoHandedWeaponProficiency,
            BrutishStrength,
            DualWield,
            Duelist,
            HonedAttack,
            Momentum,
            CrossBlock,
            BlindFighting,
            Retort,
            Maim,
            TruePiercingStrike,
            IronPalm,
            Hemorrhage,
            RiposteLine,
            LowSweep,
            GuardCleaver,
            ReaversMark,
            Brace,
            AnvilStrike,
            IronPalm2,
            Hemorrhage2,
            RiposteLine2,
            LowSweep2,
            GuardCleaver2,
            ReaversMark2,
            Brace2,
            AnvilStrike2,
        ],
    },
    "Berserker": {
        "1": [
            FinalAssault,
            Frenzy,
            Parry,
            MonkeyGrip,
            MortalStrike2,
            PainTolerance,
            HemorrhageThirst,
            Fatality,
            ComposedWrath,
            RecklessOnslaught,
            BoomerangToss,
            TectonicRift,
            ThunderousVault,
            Momentum,
            MonkeyGrip2,
            TripleStrike,
            GuardCleaver,
            ReaversMark,
            Brace,
            AnvilStrike,
            GuardCleaver2,
            ReaversMark2,
            Brace2,
            AnvilStrike2,
        ],
    },
    "Grandmaster of Arms": {
        "1": [
            DoubleStrike,
            DualWieldExcellence,
            DualWieldMastery,
            WeaponSwap,
            IronPalm,
            Hemorrhage,
            RiposteLine,
            LowSweep,
            GuardCleaver,
            ReaversMark,
            Brace,
            AnvilStrike,
            IronPalm2,
            Hemorrhage2,
            RiposteLine2,
            LowSweep2,
            GuardCleaver2,
            ReaversMark2,
            Brace2,
            AnvilStrike2,
            IronPalm3,
            Hemorrhage3,
            RiposteLine3,
            LowSweep3,
            GuardCleaver3,
            ReaversMark3,
            Brace3,
            AnvilStrike3,
        ],
    },
    "Paladin": {
        "1": [OathsJudgment, OathsShelter],
        "2": [DoubleStrike, TrueStrike, Parry],
        "3": BlessedLight,
    },
    "Crusader": {
        "1": [
            BeyondReproach,
            Censure,
            Condemnation,
            Parry,
            Penalization,
            Posturing,
            PrayerOfFaith,
            RadiantHealing,
            Sanctification,
            ShieldRicochet,
            SwordAndBoard,
            TwoHandedWeaponProficiency,
            UndeadHunter,
        ],
        "5": MortalStrike,
        "22": TripleStrike,
        "30": TruePiercingStrike,
    },
    "Lancer": {
        "1": [
            CriticalVigor,
            DragonSoul,
            ExtendedReach,
            Jump,
            LanceSweep,
            Phalanx,
            PolearmExcellence,
            PolearmProficiency,
            SwingAndBash,
            TrueStrike,
            VigilantLanding,
        ],
        "12": Zephyrstrike,
    },
    "Dragoon": {
        "1": [
            PolearmMastery,
            DragonDive,
            Dragonheart,
        ],
        "5": TruePiercingStrike,
    },
    "Sentinel": {
        "1": [
            Adrenaline,
            Boast,
            BraceWall,
            BulwarkGuard,
            Charge,
            DoubleStrike,
            FocusedAssault,
            Goad,
            HoldTheLine,
            PurgeWeakness,
            Repercussion,
            Retaliate,
            ShieldRiposte,
            SpellBlock,
            SpellReflection,
            SwingAndBash,
        ],
    },
    "Stalwart Defender": {
        "1": [
            BattleCry,
            BattleDetermination,
            Boast,
            BraceWall,
            BulwarkGuard,
            CitadelAegis,
            FocusedAssault,
            GeneratorShield,
            GetEven,
            HoldTheLine,
            IronwallReprisal,
            LastBastionSurge,
            LastStand,
            PurgeWeakness,
            Repercussion,
            Retaliate,
            ShieldRicochet,
            SpellBlock,
            SpellReflection,
            Stronghold,
            TowerOffense,
            CrushingVengeance,
            DoublePayback,
            IronMaiden,
        ],
        "18": LastStand,
    },
    "Mage": {
        "1": [
            FireInside,
            FrozenArmor,
            Electrified,
            WindCurrents,
            Refreshment,
            TerraFirma,
            ClassicalForce,
            ArcaneTradition,
            ManaShield,
            ImbueWeapon,
        ],
    },
    "Sorcerer": {
        "1": [
            ArcaneEmpowerment,
            ArcaneRitual,
            Aspirate,
            ClassicalEnrichment,
            Combustion,
            EjectionGale,
            ForceMultiplier,
            ManaLeak,
            IllusoryLink,
            Paralyzer,
            Snowpiercer,
            UnsteadyGround,
        ],
        "10": Doublecast,
    },
    "Wizard": {
        "1": [
            Aftershock,
            DetonationCascade,
            DivineWind,
            ElectricalBurns,
            ElementalConvergence,
            Fragmentation,
            Inferno,
            ManaSplinters,
            Multiplicity,
            Spaghettification,
            Subzero,
            Triplecast,
            UnrelentingWaves,
        ],
    },
    "Warlock": {
        "1": [
            Familiar,
            FamiliarBond,
            ThornByMySide,
            RestorativeBarrier,
            InsultToInjury,
            MasterLocator,
            FamiliarBond2,
            FesteringAnguish,
            VimAndRigor,
            ImpendingDemise,
        ],
        "5": HealthDrain,
        "9": LifeTap,
        "15": ManaDrain,
        "20": Familiar2,
    },
    "Shadowcaster": {
        "1": [
            Alacrity,
            Bullionaire,
            DeathBecomesUs,
            IndiscriminateProvocation,
            MortalShackles,
            NightMoves,
            NightTerror,
            PennyDreadful,
            PiercingBolt,
            ResourceAbuse,
            Sciophobia,
            TopOff,
            UnoReverseCard,
        ],
        "4": ManaTap,
        "10": HealthManaDrain,
        "20": Familiar3,
    },
    "Demonologist": {
        "1": [
            CallContract,
            FinePrint,
            ControlledCorruption,
            Patronage,
            AbyssalAuthority,
            DanceOfTheDead,
            SoulAsylum,
            ContractKiller,
            MysticalVitality,
            ContagiousBlaze,
            PersistentCorruption,
            GreaseMissile,
            SoulVessel,
            FlammableAffliction,
            MonkeysPaw,
        ],
    },
    "Spellblade": {
        "1": [
            CounterCharge,
            Breakdown,
            DoubleStrike,
            ManaSlice,
            EnhanceBlade,
            NovelShielding,
            EnhanceArmor,
            ManaTap,
            AmplifyArcane,
            AmplifyElemental,
            StorageCapacity,
            TrueStrike,
            Parry,
        ],
    },
    "Knight Enchanter": {
        "1": [DoubleStrike, EnhanceArmor, ManaTap, Parry, Riposte],
        "5": [CleavingEdge, DefensiveRelease, DispelSlash],
        "10": [ReDebuff, ThirdEye],
        "15": [ResonantStrike, AegisWeave, StorageCapacity2],
        "20": [WeaveReservoir, Spellbind],
        "25": [ManaSlice2, ArcaneRiposte, EchoingBlade],
        "30": [QuickRecharge, TruePiercingStrike, TripleStrike],
    },
    "Conjurer": {},
    "Thaumaturgist": {
        "1": [
            HealSummon,
            ConduitCommand,
            RaiseSummon,
            InvokeHodag,
            InvokeCaladrius,
            InvokePatagon,
            InvokeDilong,
            InvokeAgloolik,
            InvokeCacus,
            InvokeIzulu,
            InvokeHala,
            InvokeLamashtu,
            InvokeSeraphim,
            InvokeBardi,
            InvokeKobalos,
            InvokeTiamat,
            InvokeZahhak,
        ],
    },
    "Footpad": {
        "1": [StumbleUpon, Disarm, DualWield, Duelist, PiercingStrike, Quickstep],
        "5": [Steal, PocketSand, Backstab, IncantationComprehension],
        "10": [Lockpick, SmokeScreen, Cripple, Parry, Inspect],
        "15": [AvoidTraps, KidneyPunch, ManaDepletion, Retort],
        "20": [DoOver, AggressivePursuit, DoubleStrike, ImbueWeapon, EvasiveGuard],
        "25": [Serendipity, SleepingPowder, Obscuration, Disruption, MysticalEvasion],
    },
    "Thief": {
        "1": ScavengersEye,
        "5": Lockpick,
        "8": PilferingStrike,
        "12": GoldToss,
        "15": Mug,
        "18": TurnTheTables,
        "22": CutAndRun,
    },
    "Rogue": {
        "1": FindersKeepers,
        "3": Zephyrstrike,
        "4": CheatDeath,
        "5": SneakAttack,
        "8": KeenEye,
        "10": SlotMachine,
        "12": TripleStrike,
        "15": MasterLockpick,
        "18": DisarmTraps,
        "20": TakeItOnTheRun,
        "22": AllIn,
        "24": SnakeEyes,
        "26": DirtyTrick,
        "28": CutAndRun,
        "30": SmokeScreen,
        "32": EvasiveGuard,
    },
    "Inquisitor": {
        "1": Reveal,
        "2": PiercingStrike,
        "3": TakeNotes,
        "5": Inspect,
        "10": ExploitWeakness,
        "14": KeenEye,
        "15": ShieldBlock,
        "22": TrueStrike,
    },
    "Seeker": {
        "1": Cartography,
        "2": Inspect,
        "3": Wayfinding,
        "5": ThirdEye,
        "8": DeductiveStrike,
        "10": SurveyorsStep,
        "12": SafePassage,
        "14": ForegoneConclusion,
        "16": TripleStrike,
        "25": TruePiercingStrike,
    },
    "Assassin": {
        "1": [
            Steal,
            Lockpick,
            Disruption,
            ForGoodMeasure,
            Distract,
            TwistTheKnife,
            OffHandExcellence,
            SneakAttack,
            Maim,
            TripleStrike,
            DeathMark,
            ApplyToxin,
            ResistDeath,
            Disembowel,
            MakeToxin,
            Cutthroat,
            AvoidTraps,
            SmokeScreen,
            HiddenBlade,
            Surprise,
            Parry,
            MainGauche,
            LiveAndLearn,
            Riposte,
        ],
    },
    "Ninja": {
        "1": [
            SmokeScreen,
            TripleStrike,
            ToxicPrecision,
            Parry,
            Mug,
            Momentum,
            LingeringVenom,
            Riposte,
            FindTraps,
            MarkedShuriken,
            DeathSentence,
            Quickstep,
            SilentWalking,
            FlurryBlades,
            CoatingConservation,
            Alacrity,
            EvasiveGuard,
            SmashAndGrab,
            ExecutionRhythm,
            Potentiation,
            ShadowEvasion,
            ShadowCounter,
            ThousandCuts,
            BlackLotusMastery,
            GhostStep,
            Untouchable,
        ],
    },
    "Spell Stealer": {
        "1": StealSpell,
        "4": ImbueWeapon,
        "8": SpellbreakersCut,
        "12": StealAsWell,
        "16": BorrowedWard,
    },
    "Arcane Trickster": {
        "1": StealSpell2,
        "2": ArcaneAmbush,
        "4": ThirdEye,
        "8": VanishingAct,
        "14": FalseOpening,
    },
    "Healer": {
        "1": [
            ImbueWeapon,
            Goad,
            Lullaby,
            BeginnersLuck,
            MentalShard,
            Cacophany,
            ShieldSlam,
            Safeguarding,
            FlashBlindness,
            DefensiveRegen,
            ZenAccuracy,
            StaffProficiency,
            DelayedReaction,
            LegSweep,
            Meditation,
        ],
    },
    "Cleric": {
        "1": SanctuaryWard,
        "2": SacredMending,
        "3": DevotionalRebuke,
        "6": ShieldSlam,
        "9": BastionPrayer,
        "10": HallowedReadiness,
        "12": ShieldBlock,
        "24": PiousBounty,
        "27": TrueStrike,
    },
    "Templar": {
        "1": Parry,
        "4": PiercingStrike,
        "6": Goad,
        "8": RelicAegis,
        "12": LastStand,
        "14": Charge,
        "16": ShieldSlam,
        "18": ShieldBlock,
        "20": BastionPrayer,
        "22": DoubleStrike,
        "24": TrueStrike,
        "26": DevotionalRebuke,
        "30": TruePiercingStrike,
    },
    "Hierophant": {
        "1": StaffConduit,
        "3": ConduitStrike,
        "8": ConsecratedConduit,
        "14": GracefulIntercession,
        "20": DevotionalRebuke,
        "26": SanctuaryWard,
        "30": BastionPrayer,
    },
    "Priest": {
        "1": Supplication,
        "2": DazedOrConfused,
        "4": DefensiveRegen,
        "6": MagicalInvigoration,
        "10": ManaShield,
    },
    "Archbishop": {
        "5": Doublecast,
        "8": GreatBenediction,
        "15": ManaShield2,
    },
    "Monk": {
        "1": ChiHeal,
        "2": UnarmedProficiency,
        "3": DoubleStrike,
        "4": FlowingPalm,
        "5": LegSweep,
        "7": TrueStrike,
        "10": PurityBody,
        "11": CenteredGuard,
        "12": Uppercut,
        "14": MirrorBreath,
        "16": Headbutt,
        "18": PurgingKata,
        "20": DrunkenBrawler,
        "25": Parry,
    },
    "Master Monk": {
        "1": Evasion,
        "3": RopeADope,
        "5": Hyakuretsukyaku,
        "10": TripleStrike,
        "12": SpinningBackElbow,
        "15": PurityBody2,
        "18": MartialMastery,
        "20": Suplex,
        "25": Hadouken,
        "30": DimMak,
    },
    "Bard": {
        "1": SongValor,
        "2": SongShelter,
        "3": SongRenewal,
        "4": RhythmicStrike,
        "5": CurtainGuard,
    },
    "Troubadour": {
        "1": GrandFinale,
        "2": SyncopatedStrike,
        "3": Countermelody,
    },
    "Pathfinder": {
        "1": [
            NaturalAttunement,
            RazorTalons,
            StumbleUpon,
            Zephyrstrike,
            CautiousAssault,
            HonedAttack,
            UnnaturalPurge,
            BounceBack,
            PiercingStrike,
            Quickstep,
            Parry,
            TrueStrike,
            SpiritStrike,
            Conversion,
            VerySuperstitious,
            PrimalTrance,
            FundamentalHarmony,
            IntensifyElements,
            Chronology,
        ],
    },
    "Druid": {
        "1": [Transform, PrimalPractice],
        "15": Transform2,
        "17": MortalStrike,
    },
    "Archdruid": {
        "10": FourfoldSurge,
    },
    "Lycan": {
        "1": Transform3,
        "5": LunarRend,
        "11": Charge,
        "15": BattleCry,
        "18": [WingedPounce, DragonFang, CenterBeast],
        "25": MortalStrike2,
    },
    "Diviner": {
        "1": LearnSpell,
        "18": Doublecast,
    },
    "Astromancer": {
        "1": [LearnSpell2, AccessStorage, Tephra, SilentLucidity],
        "12": ThreadedCast,
        "25": Triplecast,
    },
    "Shaman": {
        "1": Totem,
        "3": TotemSurge,
        "4": ElementalStrike,
        "5": SpiritAnimal,
        "6": PiercingStrike,
        "7": ResonantWard,
        "8": SpiritMend,
        "10": MaelstromWeapon,
        "19": TrueStrike,
        "24": DoubleStrike,
    },
    "Soulcatcher": {
        "1": AbsorbEssence,
        "2": Parry,
        "3": TotemSurge,
        "4": SpiritClaw,
        "5": SoulRend,
        "7": AncestralAegis,
        "9": TripleStrike,
        "11": Soulstorm,
        "29": TruePiercingStrike,
    },
    "Ranger": {
        "1": [Tame, FavoredEnemy],
        "2": WildSense,
        "3": Duelist,
        "4": TwoHandedWeaponProficiency,
        "5": Parry,
        "6": TrueStrike,
        "7": AggressivePursuit,
        "8": UncannyVolley,
        "9": QuarryCleave,
        "10": HuntersSnare,
    },
    "Beast Master": {
        "5": Cover,
        "7": Zephyrstrike,
        "9": PackStrike,
        "10": GuardPartner,
        "11": HarryPrey,
        "12": MendWounds,
        "13": UnleashInstinct,
        "14": RallyPartner,
    },
}

spell_dict = {
    "Warrior": {},
    "Weapon Master": {},
    "Berserker": {},
    "Paladin": {
        "1": [Heal, DetectUndead, DetectFiend],
        "4": Smite,
        "10": RepelTheWicked,
        "15": Bless,
        "24": DivineProtection,
        "25": ResistShadow,
        "26": HallowedGround,
    },
    "Crusader": {
        "1": [DivineProtection, DivineProtection2, RepelTheWicked],
        "3": Smite2,
        "8": Heal2,
        "16": Cleanse,
        "18": Smite3,
        "20": Dispel,
    },
    "Lancer": {},
    "Dragoon": {},
    "Sentinel": {},
    "Stalwart Defender": {},
    "Mage": {
        "1": [
            Firebolt,
            IceLance,
            Shock,
            Gust,
            WaterJet,
            Tremor,
            MagicMissile,
            ManaRupture,
            Polymorph,
            Enfeeble,
            BlindingFog,
            ShadowBolt,
            InflateHealth,
            EnlivenDead,
            ConjureBlade,
            ConjureAnimal,
            ConjureShackles,
            ConjurePotion,
            Reflect,
            Sleep,
            Boost,
            MirrorImage,
        ],
    },
    "Sorcerer": {
        "1": [
            Fireball,
            Icicle,
            Lightning,
            Aqualung,
            Mudslide,
            Hurricane,
            MagicMissile2,
            ManaRupture,
            KineticExplosion,
            Boost,
            MirrorImage,
            Slow,
            Refueling,
        ],
        "16": Dispel,
        "30": IceBlock,
    },
    "Wizard": {
        "1": [
            Counterspell,
            Firestorm,
            IceBlizzard,
            Electrocution,
            Tornado,
            Tsunami,
            Earthquake,
            GravitationalPull,
            MagicMissile3,
            PhotonSphere,
            PrismaticCataclysm,
            MirrorImage2,
            Petrify,
            Teleport,
            Volitation,
        ],
    },
    "Warlock": {
        "1": [
            Sleep,
            ShadowBolt,
            Eclipse,
            ResistHoly,
            CurseUmbra,
            CurseFrailty,
            CurseSwarms,
            HemorrhagingCurse,
            Hex,
        ],
        "4": Corruption,
        "10": Terrify,
        "12": ShadowBolt2,
        "15": Doom,
        "19": Dispel,
    },
    "Shadowcaster": {
        "8": [ShadowBolt3, ShadowCurtain, SoulBinding],
        "12": Invisibility,
        "16": Nightmare,
        "18": Desoul,
    },
    "Demonologist": {
        "1": Firebolt,
        "2": Corruption2,
        "3": Netherchar,
        "4": Napalm,
        "5": SoulSiphon,
        "6": Desoul,
        "7": CurseElijah,
        "8": CurseDysarthria,
        "9": DemonEyes,
    },
    "Spellblade": {
        "1": [KineticExplosion, Reflect, Boost],
    },
    "Knight Enchanter": {
        "10": [
            Fireball,
            Icicle,
            Lightning,
            Aqualung,
            Mudslide,
            Hurricane,
            MagicMissile2,
        ],
    },
    "Conjurer": {
        "1": [FloatingCrystal, Sleep, MirrorImage, ConjureHumanoid],
        "5": [Torchlight, Silence, NightmareFuel, ConjureMonster],
        "10": [Banish, ConjureSpirit],
        "15": [WeakenMind, ConjureElixir, ConjureFiend, Volitation],
        "25": [ConjureCelestial, Teleport],
        "30": [BarrierWall, ManaBarbs, ExplosiveDecoy, ConjureDragon],
    },
    "Thaumaturgist": {
        "1": MiracleBlade,
        "2": MiracleShackles,
        "3": MiraclePotion,
        "4": MiracleCrystal,
    },
    "Footpad": {
        "5": DetectAnimal,
        "15": DetectHumanoid,
        "25": DetectSlime,
    },
    "Thief": {},
    "Rogue": {},
    "Inquisitor": {
        "3": Dispel,
        "8": Silence,
        "12": Enfeeble,
        "15": Reflect,
        "18": ResistFire,
        "19": ResistIce,
        "20": ResistElectric,
        "21": ResistWater,
        "22": ResistEarth,
        "23": ResistWind,
    },
    "Seeker": {
        "1": Teleport,
        "4": ResistAll,
        "10": Sanctuary,
        "12": Volitation,
        "14": EnterWall,
        "16": WeakenMind,
    },
    "Assassin": {
        "10": Invisibility,
    },
    "Ninja": {
        "1": [Haste, Invisibility],
    },
    "Spell Stealer": {
        "8": WindSpeed,
        "27": Silence,
    },
    "Arcane Trickster": {},
    "Healer": {
        "1": [
            Bless,
            Tranquility,
            Courage,
            Vision,
            Tutelary,
            Smite,
            TurnUndead,
            DetectUndead,
            DivineProtection,
            Heal,
            Regen,
            Heal2,
            Holy,
            IncitePanic,
            ResistShadow,
        ],
    },
    "Cleric": {
        "1": Smite,
        "5": Bless,
        "14": Cleanse,
        "15": Silence,
        "16": Smite2,
        "19": TurnUndead2,
    },
    "Templar": {
        "2": Bless,
        "6": Regen2,
        "10": Smite3,
        "14": Holy2,
        "18": Dispel,
        "22": TurnUndead2,
        "26": Cleanse,
    },
    "Hierophant": {
        "2": Heal2,
        "4": Holy2,
        "6": Smite3,
        "8": ResistShadow,
        "10": Shell,
        "12": Regen2,
        "14": Reflect,
        "16": Bless,
        "18": Dispel,
        "20": TurnUndead2,
        "22": Cleanse,
        "24": Silence,
    },
    "Priest": {
        "1": Regen2,
        "3": Holy2,
        "5": ExpelCurse,
        "6": Shell,
        "11": Cleanse,
        "15": Bless,
        "17": Dispel,
        "21": Berserk,
    },
    "Archbishop": {
        "1": Heal3,
        "4": Holy3,
        "6": Silence,
        "7": Regen3,
        "20": [Resurrection, ExpelCurse],
    },
    "Monk": {},
    "Master Monk": {},
    "Bard": {
        "1": Kaleidoscope,
        "2": InspiringVerse,
        "3": DissonantChord,
        "4": PrismaticRay,
    },
    "Troubadour": {
        "1": RallyingChorus,
        "2": ResonantWave,
        "3": PrismaticFinale,
    },
    "Pathfinder": {
        "1": [
            PoisonDart,
            Regrowth,
            RayOfMoonlight,
            NullifyPoison,
            ThornyVine,
            PoisonStrike,
            CallAnimal,
            DetectAnimal,
            CreatureComforts,
            Hydration,
            Tremor,
            WaterJet,
            Gust,
            Scorch,
            DetectElemental,
            BlindingFog,
            Geomancy,
            ControlZ,
        ],
    },
    "Druid": {
        "1": [PoisonDart, NoxiousMist, RestoringBoon, ResistPoison],
        "5": StoneSkin,
        "9": Regrowth,
        "17": [CalmingBreeze, Starfall],
    },
    "Archdruid": {
        "1": [PlantSeeds, PoisonBreath, ExpelCurse, GrovePulse],
        "4": Bolt,
        "6": VilePotion,
        "8": Windswept,
        "12": NatureShield,
        "16": BallLightning,
    },
    "Lycan": {
        "8": Dispel,
    },
    "Diviner": {
        "1": Vulcanize,
        "3": Enfeeble,
        "8": Haste,
        "14": Dispel,
        "23": [Berserk, TemporaryStasis],
    },
    "Astromancer": {
        "1": Vulcanize,
        "6": Foretell,
        "10": WeakenMind,
        "15": Boost,
        "18": TwistFate,
        "22": Wormhole,
        "28": Rewind,
    },
    "Shaman": {
        "2": Hex,
        "3": ResistFire,
        "4": ResistWater,
        "5": ResistEarth,
        "6": ResistWind,
        "9": Hydration,
        "16": AstralShift,
    },
    "Soulcatcher": {
        "4": SoulDrain,
        "6": Dispel,
        "8": Vulcanize,
        "12": Desoul,
    },
    "Ranger": {
        "1": DetectAnimal,
        "2": CreatureComforts,
        "3": Vision,
    },
    "Beast Master": {},
}


# A renamed Python catalog ability keeps its prior save/shortcut slug here.
# No aliases are currently needed, but the explicit boundary prevents a display
# rename from silently invalidating an existing assignment.
PYTHON_CATALOG_ABILITY_ID_ALIASES: dict[str, str] = {}


def _catalog_slug(value: object) -> str:
    """Return a canonical underscore slug from a unique catalog display name."""
    normalized = "".join(char.lower() if char.isalnum() else " " for char in str(value))
    return "_".join(normalized.split())


@lru_cache(maxsize=1)
def _python_catalog_ability_ids() -> tuple[dict[type, str], dict[str, type]]:
    """Build canonical identities for active Python abilities in player catalogs.

    YAML abilities own their IDs directly. Older Python implementations did
    not, so their unique learned display names are the catalog-owned canonical
    identity. Collisions fail eagerly rather than creating ambiguous shortcut
    or save references.
    """
    by_type: dict[type, str] = {}
    by_id: dict[str, type] = {}
    reserved_ids: dict[str, type] = {}
    for catalog in (skill_dict, spell_dict):
        for levels in catalog.values():
            for entry in levels.values():
                for ability_ctor in ability_classes_for(entry):
                    ability = ability_ctor()
                    if getattr(ability, "passive", False) or getattr(
                        ability, "exploration_cast", False
                    ):
                        continue
                    existing_id = getattr(ability, "ability_id", None)
                    if isinstance(existing_id, str) and existing_id:
                        reserved_ids[existing_id] = ability_ctor
                        continue
                    ability_id = _catalog_slug(getattr(ability, "name", ""))
                    if not ability_id:
                        raise RuntimeError(
                            f"Active catalog ability {ability_ctor.__name__} has no identity name."
                        )
                    if ability_id in reserved_ids:
                        raise RuntimeError(
                            f"Catalog ability identity collision for {ability_id}: "
                            f"{reserved_ids[ability_id].__name__} already owns that slug."
                        )
                    existing_ctor = by_id.get(ability_id)
                    if existing_ctor is not None and existing_ctor is not ability_ctor:
                        raise RuntimeError(
                            f"Catalog ability identity collision for {ability_id}: "
                            f"{existing_ctor.__name__} and {ability_ctor.__name__}."
                        )
                    by_type[ability_ctor] = ability_id
                    by_id[ability_id] = ability_ctor
    collisions = set(by_id).intersection(reserved_ids)
    if collisions:
        ability_id = sorted(collisions)[0]
        raise RuntimeError(
            f"Catalog ability identity collision for {ability_id}: "
            f"{reserved_ids[ability_id].__name__} already owns that slug."
        )
    return by_type, by_id


def ensure_catalog_ability_identity(ability: object) -> str | None:
    """Assign and return the stable slug for a learned catalog ability."""
    existing_id = getattr(ability, "ability_id", None)
    if isinstance(existing_id, str) and existing_id:
        return existing_id
    ability_id = _python_catalog_ability_ids()[0].get(type(ability))
    if ability_id is not None:
        ability.ability_id = ability_id
    return ability_id


def catalog_ability_from_id(ability_id: str) -> object | None:
    """Recreate a Python catalog ability from its canonical shortcut/save slug."""
    canonical_id = PYTHON_CATALOG_ABILITY_ID_ALIASES.get(ability_id, ability_id)
    ability_ctor = _python_catalog_ability_ids()[1].get(canonical_id)
    if ability_ctor is None:
        return None
    ability = ability_ctor()
    ensure_catalog_ability_identity(ability)
    return ability
